WIP: Task 6
Svvald/nodejs-aws-be pull request #5
Opened 2020-11-22 20:59 UTC by Svvald

2020-11-23 20:55 UTC, RidgeA requested changes
ping me here when the task will be done

2020-11-23 22:11 UTC, Svvald commented
@RidgeA Task is completed now, you can review it

2020-11-23 22:21 UTC, RidgeA approved these changes
4/6, see comments

2020-11-23 22:21 UTC, RidgeA commented on import-service/serverless.ts
> +      SQS_URL: 'https://sqs.eu-west-1.amazonaws.com/314054664759/catalog-items-queue'
Consider using sharing features of CloudFormation/Serverless instead of hardcoded values

2020-11-23 22:21 UTC, RidgeA commented on import-service/src/lambda/import-file-parser/import-file-parser.ts
> +class SQSStream extends Transform {
`Transform` stream is more suitable if you need to pass through data. 
In this case, `Writable` would suit better.

2020-11-23 22:21 UTC, RidgeA commented on import-service/src/lambda/import-file-parser/import-file-parser.ts
> +      s3.getObject(params).createReadStream()
You man use [finished](https://nodejs.org/dist/latest-v15.x/docs/api/stream.html#stream_stream_finished_stream_options_callback) to get rid of multiple `error` event handlers.
In conjunction with [promisify](https://nodejs.org/dist/latest-v15.x/docs/api/util.html#util_util_promisify_original) it allows writing code in "synchronous" style.

2020-11-24 18:16 UTC, Neythalion commented on product-service/src/lambda/catalog-batch-process/catalog-batch-process.ts
> +    const insertProductsQuery = format(`insert into products(title, description, price) values %L returning id`, products);
Is it work correctly with number fields such as price?

2020-12-13 14:42 UTC, merged